version: '3.9'

services:
  schemalesssqlapi:
    image: htetlinmaung/schemalesssqlapi
    build: .
    ports:
      - "8080:3000"
    environment:
      - express_handler_mode=native
      - route_prefix=schemalesssqlapi
      - db_connection=postgres://{username}:{password}@localhost:5434/schemalesssqlapi